services:
  web:
    image: mfe-markdown-http-x86:latest
    environment:
      - USER_LOGIN=${USER}
      - HASHED_PASSWORD=${HASHED_PASSWORD}
    volumes:
      - ./files:/app/files
    ports:
      - "3000:3000"
